### ISSUE TITLE
Bug: $cordovaToast.show() resolved promise object has fields "1", "2".

### ISSUE THREAD

**Issue by mseleng** [ionic-team/ng-cordova#1245]
Hi I was trying to make my toast tappable using the $cordovaToast service, using its show() method just like this:

```
$cordovaToast.show(...).then(function(result) {
    if (result && result.event) {
        // do something here, toast was tapped
    }
}, function(error) { });
```

but it doeas actually nothing. When I put some debug log just before the if, I can see, that it goes to the success callback, when the toast is shown, but there is no reaction (read no callback called) when the toast is tapped. Do you have any idea why this is happening?
When I use the cordova plugin way:

```
window.plugins.toast.show(..., function(result) {
     if (result && result.event) {
        // do something here, toast was tapped
    }
});
```

everything works just fine.
I also noticed, using the Object.keys() method called on the result object that is has only 2 fields: ["1","2"].

Thanx for the response.

**Comment by marosseleng** [comment]
Closing this as I am no longer in the field.
