### ISSUE TITLE
cordova-plugin-statusbar fails on iOS 11

### ISSUE THREAD

**Issue by stripathix** [ionic-team/ng-cordova#1434]
![simulator screen shot jun 11 2017 at 8 04 22 am](https://user-images.githubusercontent.com/8480351/27027173-006d3a74-4f7e-11e7-8c2f-d2c573cd0947.jpeg)

Cordova status bar plugin is not rendering status bar as an overlay.
Works fine on iOS 10.

Have this inside "deviceready":

$cordovaStatusbar.overlaysWebView(true);

**Comment by lterodde320** [comment]
You can temporarily fix this issue by adding this script to your body tag of your document: 

document.addEventListener("deviceready", function () { cordova.plugins.Keyboard.disableScroll(true); }, false);

**Comment by stripathix** [comment]
This issue is been fixed cordova side.
Ref: https://issues.apache.org/jira/browse/CB-12886

**Comment by vinimendes3** [comment]
@stripathix how did you solve this?
