### ISSUE TITLE
Someone should maintain this code

### ISSUE THREAD

**Issue by victorsosa** [ionic-team/ng-cordova#1442]
Hi @gortok 

One year without releases; this code is not been maintain, I could offer my help if you are not planning in keeping this code updated. There are a lot of projects depending on ngCordova.

**Comment by fendorio** [comment]
Agree, this project shouldn't be left unmaintained.

**Comment by mlynch** [comment]
Hi all, please use ionic-native which is the updated version of ngCordova: https://github.com/ionic-team/ionic-native

We support that and Version 2 of ionic-native works with Angular 1. Going forward we will be supporting Angular 1 even more as we move towards a framework agnostic future.
