### ISSUE TITLE
SQLite plugin doc

### ISSUE THREAD

**Issue by beauby** [ionic-team/ng-cordova#719]
Two problems there:
- the URL to the source file is wrong (`SQLite.js` instead of `sqlite.js`),
- the example is wrong (the `openDB` method takes two parameters, whereas the example implies that it takes a config object as a parameter).

**Comment by brodybits** [comment]
+1 this been causing confusion for people using the sqlite plugin that I am maintaining, leading to litehelpers/Cordova-sqlite-storage#229, litehelpers/Cordova-sqlite-storage#246,  litehelpers/Cordova-sqlcipher-adapter#5, and possibly litehelpers/Cordova-sqlite-storage#265.

Thanks @sebastienblanc for issuing PR #653.

**Comment by brodybits** [comment]
The code was fixed by PR #889, no need to fix the document any more. Please close this one!

**Comment by beauby** [comment]
Closing :+1:
