### ISSUE TITLE
Oauth is not found in custom build

### ISSUE THREAD

**Issue by mininao** [ionic-team/ng-cordova#934]
When using the custom build feature here : http://ngcordova.com/build/ and checking only "oauth" and "oauth tools", the following file is created : 

``` javascript
angular.module('ngCordova', [
  'ngCordova.plugins'
]);

angular.module('ngCordova.plugins', [
     'oauth',
     'oauthUtility'
]);

//#### Begin Individual Plugin Code ####

Not FoundNot Found
```

Maybe this is related to the fact that oauth is in a submodule ?

**Comment by mhartington** [comment]
Since OAuth is a submodle, it would have to be installed separately.

**Comment by mininao** [comment]
Alright ! Maybe it should be removed from the custom build feature then ?

**Comment by gortok** [comment]
OAuth will be removed from version 0.2.0. (next release); I'll include notes on how to install it if you want it.

**Comment by mininao** [comment]
Cool, thanks ;)

**Comment by nraboy** [comment]
Is it being removed from the custom builder or ng-cordova entirely?

**Comment by mhartington** [comment]
It will be removed completely. We will point to your repo instead

**Comment by nraboy** [comment]
Fair enough.  Thanks for clarification :-)
